/**
 * ARCfund MXE Anchor Program
 * ==========================
 * 
 * Solana Anchor program that integrates with Arcium MXE for
 * encrypted project pitches and access control.
 * 
 * This program handles:
 * 1. Project creation with optional encryption
 * 2. Access request management
 * 3. Access approval/revocation
 * 4. Callbacks from MXE computations
 * 
 * Deployment: Use `arcium deploy` command in WSL2/Linux
 */

use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;

// Computation definition offsets - generated by Arcium build
const COMP_DEF_OFFSET_ENCRYPT_PROJECT: u32 = comp_def_offset!("encrypt_project");
const COMP_DEF_OFFSET_VERIFY_ACCESS: u32 = comp_def_offset!("verify_access");

// NOTE: This will be auto-replaced during deployment
// Run `arcium build` to generate the actual program ID
declare_id!("ARCfundMXEProgram11111111111111111111111111");

/// ARCfund MXE Program
#[arcium_program]
pub mod arcfund_mxe {
    use super::*;

    // ========================================================================
    // Initialization Instructions
    // ========================================================================

    /// Initialize the encrypt_project computation definition
    /// 
    /// This must be called once after deployment to register the
    /// encrypt_project encrypted instruction with the MXE.
    pub fn init_encrypt_project_comp_def(
        ctx: Context<InitEncryptProjectCompDef>
    ) -> Result<()> {
        init_comp_def(ctx.accounts, None, None)?;
        msg!("Initialized encrypt_project computation definition");
        Ok(())
    }

    /// Initialize the verify_access computation definition
    pub fn init_verify_access_comp_def(
        ctx: Context<InitVerifyAccessCompDef>
    ) -> Result<()> {
        init_comp_def(ctx.accounts, None, None)?;
        msg!("Initialized verify_access computation definition");
        Ok(())
    }

    // ========================================================================
    // Project Management Instructions
    // ========================================================================

    /// Create a new project
    /// 
    /// For public projects:
    /// - Simply creates the on-chain account
    /// 
    /// For private projects:
    /// - Queues encryption computation with MXE
    /// - Stores encrypted reference after callback
    /// 
    /// # Arguments
    /// * `project_id` - Unique 32-byte project identifier
    /// * `title` - Project title (max 64 chars)
    /// * `is_private` - Whether to encrypt the pitch
    /// * `computation_offset` - Random offset for MXE (if private)
    /// * `encrypted_chunks` - Pre-encrypted pitch chunks (if private)
    /// * `x25519_pubkey` - Client's ephemeral pubkey for encryption
    /// * `nonce` - Encryption nonce
    pub fn create_project(
        ctx: Context<CreateProject>,
        project_id: [u8; 32],
        title: String,
        is_private: bool,
        computation_offset: Option<u64>,
        encrypted_chunks: Option<Vec<[u8; 32]>>,
        x25519_pubkey: Option<[u8; 32]>,
        nonce: Option<u128>,
    ) -> Result<()> {
        require!(title.len() <= Project::MAX_TITLE_LEN, ErrorCode::TitleTooLong);

        let project = &mut ctx.accounts.project;
        project.id = project_id;
        project.founder = ctx.accounts.founder.key();
        project.title = title.clone();
        project.is_private = is_private;
        project.encrypted_ref = None;
        project.created_at = Clock::get()?.unix_timestamp;
        project.bump = ctx.bumps.project;

        if is_private {
            // Validate required parameters for private projects
            require!(computation_offset.is_some(), ErrorCode::MissingComputationOffset);
            require!(encrypted_chunks.is_some(), ErrorCode::MissingEncryptedData);
            require!(x25519_pubkey.is_some(), ErrorCode::MissingPublicKey);
            require!(nonce.is_some(), ErrorCode::MissingNonce);

            let chunks = encrypted_chunks.unwrap();
            require!(chunks.len() == 8, ErrorCode::InvalidChunkCount);

            // Build arguments for MXE computation
            let mut arg_builder = ArgBuilder::new()
                .x25519_pubkey(x25519_pubkey.unwrap())
                .plaintext_u128(nonce.unwrap());
            
            for chunk in chunks.iter() {
                arg_builder = arg_builder.encrypted_bytes32(*chunk);
            }

            // Initialize sign PDA for callbacks
            ctx.accounts.sign_pda_account.bump = ctx.bumps.sign_pda_account;

            // Queue the encryption computation
            queue_computation(
                ctx.accounts.into(),
                computation_offset.unwrap(),
                arg_builder.build(),
                None, // No callback offset
                vec![CreateProjectCallback::callback_ix(
                    computation_offset.unwrap(),
                    &ctx.accounts.mxe_account,
                    &[project_id]
                )?],
                1,  // Priority
                0,  // Tip
            )?;

            msg!("Queued encryption computation for project: {:?}", project_id);
        }

        emit!(ProjectCreated {
            project_id,
            founder: ctx.accounts.founder.key(),
            title,
            is_private,
            timestamp: project.created_at,
        });

        Ok(())
    }

    /// Callback after encryption computation completes
    /// 
    /// This is called by the MXE after processing the encrypt_project
    /// computation. It stores the encrypted reference on-chain.
    #[arcium_callback(encrypted_ix = "encrypt_project")]
    pub fn create_project_callback(
        ctx: Context<CreateProjectCallback>,
        output: SignedComputationOutputs<EncryptProjectOutput>,
    ) -> Result<()> {
        // Verify the computation output
        let result = output.verify_output(
            &ctx.accounts.cluster_account,
            &ctx.accounts.computation_account
        )?;

        // Store encrypted reference
        let encrypted_ref = result.field_0.ciphertexts[0];

        emit!(ProjectEncrypted {
            project_id: ctx.accounts.project.id,
            encrypted_ref,
            nonce: result.field_0.nonce.to_le_bytes(),
        });

        msg!("Project encryption completed: {:?}", encrypted_ref);

        Ok(())
    }

    // ========================================================================
    // Access Management Instructions
    // ========================================================================

    /// Request access to a private project
    /// 
    /// Creates an AccessRequest account that the founder can approve or reject.
    pub fn request_access(
        ctx: Context<RequestAccess>,
        project_id: [u8; 32],
        message: Option<String>,
    ) -> Result<()> {
        let request = &mut ctx.accounts.access_request;
        request.project = ctx.accounts.project.key();
        request.investor = ctx.accounts.investor.key();
        request.status = AccessStatus::Pending;
        request.message = message.unwrap_or_default();
        request.created_at = Clock::get()?.unix_timestamp;
        request.responded_at = None;
        request.bump = ctx.bumps.access_request;

        emit!(AccessRequested {
            project_id,
            investor: ctx.accounts.investor.key(),
            timestamp: request.created_at,
        });

        Ok(())
    }

    /// Approve an access request
    /// 
    /// Creates an AccessPermission account that grants the investor
    /// access to decrypt the project pitch.
    pub fn approve_access(
        ctx: Context<ApproveAccess>,
        project_id: [u8; 32],
    ) -> Result<()> {
        // Update request status
        let request = &mut ctx.accounts.access_request;
        request.status = AccessStatus::Approved;
        request.responded_at = Some(Clock::get()?.unix_timestamp);

        // Create permission
        let permission = &mut ctx.accounts.access_permission;
        permission.project = ctx.accounts.project.key();
        permission.investor = ctx.accounts.access_request.investor;
        permission.granted_at = Clock::get()?.unix_timestamp;
        permission.bump = ctx.bumps.access_permission;

        emit!(AccessGranted {
            project_id,
            investor: permission.investor,
            timestamp: permission.granted_at,
        });

        Ok(())
    }

    /// Reject an access request
    pub fn reject_access(
        ctx: Context<RejectAccess>,
        _project_id: [u8; 32],
    ) -> Result<()> {
        let request = &mut ctx.accounts.access_request;
        request.status = AccessStatus::Rejected;
        request.responded_at = Some(Clock::get()?.unix_timestamp);

        emit!(AccessRejected {
            project: ctx.accounts.project.key(),
            investor: request.investor,
        });

        Ok(())
    }

    /// Revoke previously granted access
    pub fn revoke_access(
        ctx: Context<RevokeAccess>,
        _project_id: [u8; 32],
    ) -> Result<()> {
        let investor = ctx.accounts.access_permission.investor;

        emit!(AccessRevoked {
            project: ctx.accounts.project.key(),
            investor,
        });

        // Account is closed via close constraint

        Ok(())
    }

    /// Check if an investor has access (view function)
    pub fn has_access(
        ctx: Context<HasAccess>,
        _project_id: [u8; 32],
    ) -> Result<bool> {
        // If the permission account exists, access is granted
        Ok(true)
    }
}

// ============================================================================
// Account Structures
// ============================================================================

/// On-chain project account
#[account]
pub struct Project {
    /// Unique project identifier (32 bytes)
    pub id: [u8; 32],
    /// Founder's wallet address
    pub founder: Pubkey,
    /// Project title (max 64 chars)
    pub title: String,
    /// Whether the pitch is encrypted
    pub is_private: bool,
    /// Reference to encrypted data (if private)
    pub encrypted_ref: Option<[u8; 32]>,
    /// Unix timestamp of creation
    pub created_at: i64,
    /// PDA bump
    pub bump: u8,
}

impl Project {
    pub const MAX_TITLE_LEN: usize = 64;
    pub const LEN: usize = 8  // discriminator
        + 32                   // id
        + 32                   // founder
        + 4 + Self::MAX_TITLE_LEN  // title (String)
        + 1                    // is_private
        + 1 + 32               // encrypted_ref (Option)
        + 8                    // created_at
        + 1;                   // bump
}

/// Access request status
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, PartialEq, Eq)]
pub enum AccessStatus {
    Pending,
    Approved,
    Rejected,
}

/// Access request from investor to founder
#[account]
pub struct AccessRequest {
    /// Project being requested
    pub project: Pubkey,
    /// Investor requesting access
    pub investor: Pubkey,
    /// Current status
    pub status: AccessStatus,
    /// Optional message from investor
    pub message: String,
    /// When request was created
    pub created_at: i64,
    /// When founder responded
    pub responded_at: Option<i64>,
    /// PDA bump
    pub bump: u8,
}

impl AccessRequest {
    pub const MAX_MESSAGE_LEN: usize = 256;
    pub const LEN: usize = 8  // discriminator
        + 32                   // project
        + 32                   // investor
        + 1                    // status
        + 4 + Self::MAX_MESSAGE_LEN  // message
        + 8                    // created_at
        + 1 + 8                // responded_at (Option)
        + 1;                   // bump
}

/// Granted access permission
#[account]
pub struct AccessPermission {
    /// Project with granted access
    pub project: Pubkey,
    /// Investor with access
    pub investor: Pubkey,
    /// When access was granted
    pub granted_at: i64,
    /// PDA bump
    pub bump: u8,
}

impl AccessPermission {
    pub const LEN: usize = 8  // discriminator
        + 32                   // project
        + 32                   // investor
        + 8                    // granted_at
        + 1;                   // bump
}

// ============================================================================
// Context Structures
// ============================================================================

/// Context for initializing encrypt_project computation definition
#[derive(Accounts)]
pub struct InitEncryptProjectCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    
    // Arcium accounts - generated by arcium_macros
    #[account(mut)]
    pub comp_def: AccountInfo<'info>,
    
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

/// Context for initializing verify_access computation definition
#[derive(Accounts)]
pub struct InitVerifyAccessCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    
    #[account(mut)]
    pub comp_def: AccountInfo<'info>,
    
    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

/// Context for creating a project
#[derive(Accounts)]
#[instruction(project_id: [u8; 32])]
pub struct CreateProject<'info> {
    #[account(mut)]
    pub founder: Signer<'info>,

    #[account(
        init,
        payer = founder,
        space = Project::LEN,
        seeds = [b"project", project_id.as_ref()],
        bump
    )]
    pub project: Account<'info, Project>,

    /// Sign PDA for Arcium callbacks
    #[account(
        init_if_needed,
        space = 9,
        payer = founder,
        seeds = [&SIGN_PDA_SEED],
        bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,

    /// MXE account for computation
    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,

    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

/// Context for encryption callback
#[derive(Accounts)]
pub struct CreateProjectCallback<'info> {
    #[account(mut)]
    pub project: Account<'info, Project>,

    pub cluster_account: Account<'info, ClusterAccount>,
    pub computation_account: Account<'info, ComputationAccount>,
}

/// Context for requesting access
#[derive(Accounts)]
#[instruction(project_id: [u8; 32])]
pub struct RequestAccess<'info> {
    #[account(mut)]
    pub investor: Signer<'info>,

    #[account(
        seeds = [b"project", project_id.as_ref()],
        bump = project.bump,
        constraint = project.is_private @ ErrorCode::ProjectNotPrivate
    )]
    pub project: Account<'info, Project>,

    #[account(
        init,
        payer = investor,
        space = AccessRequest::LEN,
        seeds = [b"request", project.key().as_ref(), investor.key().as_ref()],
        bump
    )]
    pub access_request: Account<'info, AccessRequest>,

    pub system_program: Program<'info, System>,
}

/// Context for approving access
#[derive(Accounts)]
#[instruction(project_id: [u8; 32])]
pub struct ApproveAccess<'info> {
    #[account(mut)]
    pub founder: Signer<'info>,

    #[account(
        has_one = founder,
        seeds = [b"project", project_id.as_ref()],
        bump = project.bump
    )]
    pub project: Account<'info, Project>,

    #[account(
        mut,
        seeds = [b"request", project.key().as_ref(), access_request.investor.as_ref()],
        bump = access_request.bump,
        constraint = access_request.status == AccessStatus::Pending @ ErrorCode::RequestNotPending
    )]
    pub access_request: Account<'info, AccessRequest>,

    #[account(
        init,
        payer = founder,
        space = AccessPermission::LEN,
        seeds = [b"access", project.key().as_ref(), access_request.investor.as_ref()],
        bump
    )]
    pub access_permission: Account<'info, AccessPermission>,

    pub system_program: Program<'info, System>,
}

/// Context for rejecting access
#[derive(Accounts)]
#[instruction(project_id: [u8; 32])]
pub struct RejectAccess<'info> {
    #[account(mut)]
    pub founder: Signer<'info>,

    #[account(
        has_one = founder,
        seeds = [b"project", project_id.as_ref()],
        bump = project.bump
    )]
    pub project: Account<'info, Project>,

    #[account(
        mut,
        seeds = [b"request", project.key().as_ref(), access_request.investor.as_ref()],
        bump = access_request.bump,
        constraint = access_request.status == AccessStatus::Pending @ ErrorCode::RequestNotPending
    )]
    pub access_request: Account<'info, AccessRequest>,
}

/// Context for revoking access
#[derive(Accounts)]
#[instruction(project_id: [u8; 32])]
pub struct RevokeAccess<'info> {
    #[account(mut)]
    pub founder: Signer<'info>,

    #[account(
        has_one = founder,
        seeds = [b"project", project_id.as_ref()],
        bump = project.bump
    )]
    pub project: Account<'info, Project>,

    #[account(
        mut,
        close = founder,
        seeds = [b"access", project.key().as_ref(), access_permission.investor.as_ref()],
        bump = access_permission.bump
    )]
    pub access_permission: Account<'info, AccessPermission>,
}

/// Context for checking access
#[derive(Accounts)]
#[instruction(project_id: [u8; 32])]
pub struct HasAccess<'info> {
    #[account(
        seeds = [b"project", project_id.as_ref()],
        bump = project.bump
    )]
    pub project: Account<'info, Project>,

    /// CHECK: Investor to check access for
    pub investor: AccountInfo<'info>,

    #[account(
        seeds = [b"access", project.key().as_ref(), investor.key().as_ref()],
        bump = access_permission.bump
    )]
    pub access_permission: Account<'info, AccessPermission>,
}

// ============================================================================
// Events
// ============================================================================

#[event]
pub struct ProjectCreated {
    pub project_id: [u8; 32],
    pub founder: Pubkey,
    pub title: String,
    pub is_private: bool,
    pub timestamp: i64,
}

#[event]
pub struct ProjectEncrypted {
    pub project_id: [u8; 32],
    pub encrypted_ref: [u8; 32],
    pub nonce: [u8; 16],
}

#[event]
pub struct AccessRequested {
    pub project_id: [u8; 32],
    pub investor: Pubkey,
    pub timestamp: i64,
}

#[event]
pub struct AccessGranted {
    pub project_id: [u8; 32],
    pub investor: Pubkey,
    pub timestamp: i64,
}

#[event]
pub struct AccessRejected {
    pub project: Pubkey,
    pub investor: Pubkey,
}

#[event]
pub struct AccessRevoked {
    pub project: Pubkey,
    pub investor: Pubkey,
}

// ============================================================================
// Errors
// ============================================================================

#[error_code]
pub enum ErrorCode {
    #[msg("Title exceeds maximum length of 64 characters")]
    TitleTooLong,
    
    #[msg("Missing computation offset for private project")]
    MissingComputationOffset,
    
    #[msg("Missing encrypted data for private project")]
    MissingEncryptedData,
    
    #[msg("Missing public key for encryption")]
    MissingPublicKey,
    
    #[msg("Missing nonce for encryption")]
    MissingNonce,
    
    #[msg("Invalid number of encrypted chunks, expected 8")]
    InvalidChunkCount,
    
    #[msg("Project is not private")]
    ProjectNotPrivate,
    
    #[msg("Access request is not pending")]
    RequestNotPending,
    
    #[msg("Unauthorized access")]
    Unauthorized,
    
    #[msg("Computation was aborted")]
    ComputationAborted,
}
